services:
  - type: web
    name: luma-gallery
    env: node
    region: oregon
    plan: free
    repo: https://github.com/2400080268/LUMAULTIMATE
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
